import type { CSSProperties } from 'react';
import { NAVBAR_HEIGHT } from '../../constants';
import { colors, fontSize, fontWeight, borderRadius } from '../../styles/tokens';

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: `calc(100vh - ${NAVBAR_HEIGHT}px)`,
    backgroundColor: colors.bgBase,
    color: colors.textPrimary,
    fontFamily: "'Inter', sans-serif",
  },
  header: {
    backgroundColor: colors.bgCard,
    borderBottom: `1px solid ${colors.borderSubtle}`,
    padding: '48px 40px',
    position: 'relative',
    overflow: 'hidden',
  },
  glow: {
    position: 'absolute',
    top: '-60px',
    right: '5%',
    width: '300px',
    height: '300px',
    borderRadius: borderRadius.circle,
    background: 'radial-gradient(circle, rgba(8,217,214,0.08) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  eyebrow: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    letterSpacing: '3.2px',
    textTransform: 'uppercase',
    color: colors.textSecondary,
    marginBottom: '8px',
  },
  heading: {
    fontSize: fontSize.display3,
    fontWeight: fontWeight.black,
    color: colors.textPrimary,
    lineHeight: 1.1,
  },
  content: {
    maxWidth: '860px',
    margin: '0 auto',
    padding: '40px',
  },
  emptyState: {
    textAlign: 'center',
    padding: '80px 20px',
  },
  emptyIcon: {
    fontSize: '48px',
    marginBottom: '16px',
  },
  emptyTitle: {
    fontSize: fontSize.xl8,
    fontWeight: fontWeight.bold,
    color: colors.textPrimary,
    marginBottom: '8px',
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: fontSize.lg,
    marginBottom: '24px',
  },
  emptyBtn: {
    display: 'inline-block',
    padding: '12px 28px',
    borderRadius: borderRadius.sm,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    cursor: 'pointer',
    border: 'none',
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  card: {
    display: 'flex',
    gap: '16px',
    backgroundColor: colors.bgCard,
    border: `1px solid ${colors.borderDefault}`,
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
    padding: '16px',
    alignItems: 'flex-start',
  },
  cardImg: {
    width: '120px',
    height: '80px',
    objectFit: 'cover',
    borderRadius: borderRadius.md,
    flexShrink: 0,
  },
  cardImgPlaceholder: {
    width: '120px',
    height: '80px',
    borderRadius: borderRadius.md,
    backgroundColor: colors.borderSubtle,
    flexShrink: 0,
  },
  cardBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    flex: 1,
    minWidth: 0,
  },
  cardTitle: {
    fontSize: fontSize.xl4,
    fontWeight: fontWeight.bold,
    color: colors.textPrimary,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  cardMeta: {
    fontSize: fontSize.md,
    color: colors.textMuted,
  },
  cardTickets: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    marginTop: '2px',
  },
  cardActions: {
    display: 'flex',
    gap: '8px',
    marginTop: '10px',
  },
  viewBtn: {
    backgroundColor: 'transparent',
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textMuted,
    padding: '6px 14px',
    borderRadius: borderRadius.sm,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    cursor: 'pointer',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  editBtn: {
    backgroundColor: 'transparent',
    border: `1px solid ${colors.secondary}`,
    color: colors.secondary,
    padding: '6px 14px',
    borderRadius: borderRadius.sm,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    cursor: 'pointer',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  priceBadge: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    marginLeft: 'auto',
    flexShrink: 0,
    alignSelf: 'flex-start',
    paddingTop: '2px',
  },
};
