import type { CSSProperties } from 'react';
import { NAVBAR_HEIGHT } from '../../constants';
import { colors, fontSize, fontWeight, borderRadius } from '../../styles/tokens';

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: `calc(100vh - ${NAVBAR_HEIGHT}px)`,
    backgroundColor: colors.bgBase,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 20px',
    position: 'relative',
    overflow: 'hidden',
  },
  glow1: {
    position: 'absolute',
    top: '-80px',
    left: '50%',
    transform: 'translateX(-50%)',
    width: '400px',
    height: '400px',
    borderRadius: borderRadius.circle,
    background: 'radial-gradient(circle, rgba(255,46,99,0.12) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  glow2: {
    position: 'absolute',
    bottom: '-80px',
    right: '10%',
    width: '300px',
    height: '300px',
    borderRadius: borderRadius.circle,
    background: 'radial-gradient(circle, rgba(8,217,214,0.1) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  card: {
    backgroundColor: colors.bgCard,
    border: `1px solid ${colors.borderDefault}`,
    borderRadius: borderRadius.xxl,
    padding: '48px 40px',
    width: '100%',
    maxWidth: '420px',
    position: 'relative',
    zIndex: 1,
  },
  eyebrow: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    letterSpacing: '3.2px',
    textTransform: 'uppercase',
    color: colors.textSecondary,
    marginBottom: '8px',
  },
  heading: {
    fontSize: fontSize.display2,
    fontWeight: fontWeight.black,
    color: colors.textPrimary,
    marginBottom: '32px',
    lineHeight: 1.1,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.textSecondary,
    letterSpacing: '1.6px',
    textTransform: 'uppercase',
  },
  input: {
    backgroundColor: colors.bgBase,
    border: `1px solid ${colors.borderDefault}`,
    borderRadius: borderRadius.md,
    padding: '13px 16px',
    color: colors.textPrimary,
    fontSize: fontSize.xl,
    width: '100%',
    boxSizing: 'border-box',
    outline: 'none',
  },
  error: {
    color: colors.primary,
    fontSize: fontSize.sm,
    marginTop: '-4px',
  },
  submitBtn: {
    marginTop: '8px',
    width: '100%',
    padding: '14px',
    borderRadius: borderRadius.md,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    letterSpacing: '1.3px',
    cursor: 'pointer',
    border: 'none',
  },
  footer: {
    marginTop: '24px',
    textAlign: 'center',
    fontSize: fontSize.md,
    color: colors.textMuted,
  },
  link: {
    color: colors.secondary,
    textDecoration: 'none',
    fontWeight: fontWeight.semibold,
  },
};
