import type { CSSProperties } from 'react';
import { colors, fontSize, fontWeight, borderRadius, zIndex } from '../../styles/tokens';

export const styles: Record<string, CSSProperties> = {
  wrapper: {
    position: 'sticky',
    top: 0,
    zIndex: zIndex.navbar,
  },
  nav: {
    height: '64px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 40px',
    backgroundColor: colors.bgNavbar,
    backdropFilter: 'blur(16px)',
    borderBottom: `1px solid ${colors.borderSubtle}`,
  },
  backBtn: {
    position: 'absolute',
    top: '100%',
    left: '40px',
    marginTop: '16px',
    backgroundColor: colors.bgNavbar,
    backdropFilter: 'blur(16px)',
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textPrimary,
    borderRadius: borderRadius.sm,
    padding: '6px 14px',
    fontSize: fontSize.md,
    cursor: 'pointer',
  },
  logo: {
    fontSize: fontSize.xl6,
    fontWeight: fontWeight.black,
    letterSpacing: '2.4px',
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  logoPrimary: { color: colors.primary },
  logoSecondary: { color: colors.secondary },
  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  createBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'transparent',
    border: `1px solid ${colors.secondary}`,
    color: colors.secondary,
    padding: '8px 19px',
    borderRadius: borderRadius.sm,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    cursor: 'pointer',
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
  },
  loginBtn: {
    backgroundColor: 'transparent',
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textMuted,
    padding: '8px 16px',
    borderRadius: borderRadius.sm,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    cursor: 'pointer',
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
  },
  myEventsBtn: {
    backgroundColor: 'transparent',
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textMuted,
    padding: '8px 16px',
    borderRadius: borderRadius.sm,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    cursor: 'pointer',
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
  },
  logoutBtn: {
    backgroundColor: 'transparent',
    border: 'none',
    color: colors.textMuted,
    fontSize: fontSize.md,
    cursor: 'pointer',
    padding: '8px 4px',
  },
  userPill: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  avatar: {
    width: '32px',
    height: '32px',
    borderRadius: borderRadius.circle,
    backgroundColor: colors.primaryBg,
    border: `1px solid ${colors.primaryBorder}`,
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userName: {
    color: colors.textMuted,
    fontSize: fontSize.md,
  },
};
